#!/usr/bin/env python3
"""Regenerate the acl-owned rename copies of quack server TUs (spec 063).

The embedded quack server (third_party/quack, pinned) reads a handful of `quack_*`
extension settings and drains client streams through a `scan_data_from_quack_client`
table function. For a clean co-load with a standalone quack (Strategy B, spec 063)
everything acl registers is `acl_quack_*`-named — so the embedded server must READ the
acl_-prefixed names. These few TUs carry those literals; this script copies them from
the submodule and rewrites ONLY those exact literals, leaving all logic untouched.

Run after bumping the `third_party/quack` submodule:  python3 src/quack_embed/sync.py
It overwrites src/quack_embed/<file> and fails loudly if an expected literal is gone
(upstream moved it — re-audit the read sites before trusting the rename).

The http server (acl_quack_http_server.cpp) is NOT generated here: it carries real
logic changes (TLS, /.well-known, public bind, registry) and is hand-maintained.
"""
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SUB = ROOT / "third_party" / "quack" / "src"
OUT = ROOT / "src" / "quack_embed"

# Exact literal renames applied to every generated file. Setting names and the drain
# function name only — never a blanket quack_ -> acl_quack_ (that would corrupt error
# messages, wire tags and class-name strings).
RENAMES = {
    '"quack_authentication_function"': '"acl_quack_authentication_function"',
    '"quack_authorization_function"': '"acl_quack_authorization_function"',
    '"quack_prepare_inline_rows"': '"acl_quack_prepare_inline_rows"',
    '"quack_debug_emit_delay_ms"': '"acl_quack_debug_emit_delay_ms"',
    '"quack_target_batch_bytes"': '"acl_quack_target_batch_bytes"',
    '"quack_rebalance_buffer_bytes"': '"acl_quack_rebalance_buffer_bytes"',
    '"quack_fetch_producer_buffer_bytes"': '"acl_quack_fetch_producer_buffer_bytes"',
    '"quack_enable_reconnects"': '"acl_quack_enable_reconnects"',
    '"quack_cache_max_rows"': '"acl_quack_cache_max_rows"',
    '"quack_result_ttl"': '"acl_quack_result_ttl"',
    # bare token (unquoted): the drain name appears inside an "INSERT ... FROM <name>(%s)"
    # format string, in the function registration, and in error text — rename all, consistently.
    'scan_data_from_quack_client': 'acl_quack_scan_data',
}

# file -> the subset of RENAMES that MUST appear in it (guard against silent drift)
FILES = {
    "quack_server.cpp": [
        '"quack_authentication_function"', '"quack_authorization_function"',
        '"quack_prepare_inline_rows"', '"quack_fetch_producer_buffer_bytes"',
        'scan_data_from_quack_client',
    ],
    "quack_result_cache.cpp": [
        '"quack_enable_reconnects"', '"quack_cache_max_rows"', '"quack_result_ttl"',
    ],
    "quack_fetch_collector.cpp": ['"quack_debug_emit_delay_ms"'],
    "quack_rebalancer_sink.cpp": ['"quack_target_batch_bytes"', '"quack_rebalance_buffer_bytes"'],
    "quack_scan_from_client.cpp": ['"scan_data_from_quack_client"'],
}

BANNER = (
    "//===----------------------------------------------------------------------===//\n"
    "// GENERATED by src/quack_embed/sync.py from third_party/quack — DO NOT EDIT.\n"
    "// acl-owned rename copy (spec 063): the embedded quack server reads acl_quack_*\n"
    "// settings and drains through acl_quack_scan_data so a standalone quack can be\n"
    "// co-loaded without a registration clash. Regenerate after a submodule bump.\n"
    "//===----------------------------------------------------------------------===//\n"
)


def main():
    failures = []
    for name, required in FILES.items():
        src = SUB / name
        if not src.exists():
            failures.append(f"{name}: source missing at {src}")
            continue
        text = src.read_text()
        for lit in required:
            if lit not in text:
                failures.append(f"{name}: expected literal {lit} not found (upstream moved it?)")
        out = text
        for a, b in RENAMES.items():
            out = out.replace(a, b)
        dest = OUT / ("acl_embed_" + name[len("quack_"):] if name.startswith("quack_") else name)
        dest.write_text(BANNER + out)
        # quack is formatted with its own duckdb pin's .clang-format, which differs from ours just
        # enough that a few files fail the CI check. Normalise to OUR pinned clang-format (11.0.1) so
        # the generated files stay clean on every regeneration.
        if shutil.which("clang-format"):
            subprocess.run(["clang-format", "-i", str(dest)], check=True)
        print(f"generated {dest.relative_to(ROOT)}")
    if failures:
        print("\nSYNC FAILED:", file=sys.stderr)
        for f in failures:
            print("  -", f, file=sys.stderr)
        sys.exit(1)
    print("ok")


if __name__ == "__main__":
    main()
