-- duckdb-acl schema migration: v19 -> v20 (spec 116, quoted names).
-- min_reader: 20 - v20 names may hold a quoted part (`"a.b"`) and compare case-insensitively; a v19 build would read such a part as a path and compare exactly, so it must not serve a v20 catalog (spec 094)
-- Run against the database that holds the `acl` policy schema, then re-open with acl_use_db.
-- Written for the duckdb dialect; see schema/acl_schema.sql for what another engine may need changing.
-- No table changes: no name stored before v20 can hold a `.` or a `"` inside a part, so every stored
-- name already is its canonical key. What v20 changes is the comparison - names compare
-- case-insensitively, as duckdb's catalog does - so the step refuses while one name is spelled several
-- ways (a catalog, a schema path at any level, an object, a reference): v20 would read them as one.
-- The error lists them; rename or drop all but one spelling, then migrate.
WITH RECURSIVE named(vcat, name) AS (SELECT "vcat" AS vcat, "vname" AS name FROM acl."relations" UNION ALL SELECT "vcat" AS vcat, "vname" AS name FROM acl."functions" UNION ALL SELECT "vcat" AS vcat, "path" AS name FROM acl."schemas" UNION ALL SELECT "vcat" AS vcat, "vname" AS name FROM acl."role_object_caps" UNION ALL SELECT "vcat" AS vcat, "schema_path" AS name FROM acl."role_schemas" UNION ALL SELECT "vcat" AS vcat, "vname" AS name FROM acl."object_columns" UNION ALL SELECT "vcat" AS vcat, "vname" AS name FROM acl."relation_columns" UNION ALL SELECT "vcat" AS vcat, "vname" AS name FROM acl."relation_types" UNION ALL SELECT "vcat" AS vcat, "vname" AS name FROM acl."keys" UNION ALL SELECT "vcat" AS vcat, "vname" AS name FROM acl."grant_columns"), up(vcat, name) AS (SELECT vcat, name FROM named WHERE name IS NOT NULL AND name <> '' UNION SELECT vcat, CASE WHEN length(regexp_extract(name, '(?:^|[.])("(?:[^"]|"")*"|[^."]*)$', 1)) >= length(name) THEN '' ELSE substr(name, 1, length(name) - length(regexp_extract(name, '(?:^|[.])("(?:[^"]|"")*"|[^."]*)$', 1)) - 1) END FROM up WHERE CASE WHEN length(regexp_extract(name, '(?:^|[.])("(?:[^"]|"")*"|[^."]*)$', 1)) >= length(name) THEN '' ELSE substr(name, 1, length(name) - length(regexp_extract(name, '(?:^|[.])("(?:[^"]|"")*"|[^."]*)$', 1)) - 1) END <> ''), spelled(kind, vcat, name) AS (SELECT 'name', vcat, name FROM up UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."catalogs" UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."role_catalogs" UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."relations" UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."functions" UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."schemas" UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."role_object_caps" UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."role_schemas" UNION SELECT 'catalog' AS kind, '' AS vcat, "vcat" AS name FROM acl."references" UNION SELECT 'reference', "vcat", "name" FROM acl."references"), clashes AS (SELECT kind || ' ' || string_agg(DISTINCT CASE WHEN kind = 'catalog' THEN name ELSE vcat || '.' || name END, ' / ' ORDER BY CASE WHEN kind = 'catalog' THEN name ELSE vcat || '.' || name END) AS spellings FROM spelled WHERE name IS NOT NULL GROUP BY kind, translate(vcat, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), translate(name, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') HAVING count(DISTINCT name) > 1 UNION ALL SELECT 'unreadable ' || kind || ' ' || CASE WHEN kind = 'catalog' THEN name ELSE vcat || ' / ' || name END FROM (SELECT 'name' AS kind, vcat, name FROM named UNION SELECT kind, vcat, name FROM spelled WHERE kind <> 'name') WHERE name IS NOT NULL AND name <> '' AND NOT regexp_matches(name, '^("(?:[^"]|"")+"|[^."]+)([.]("(?:[^"]|"")+"|[^."]+))*$'))
SELECT CASE WHEN count(*) > 0 THEN error('v20 compares names case-insensitively (spec 116), and these are spelled several ways - or are not names at all (a part with a stray quote, an empty part): rename or drop all but one spelling, fix each unreadable one, then migrate: ' || string_agg(spellings, '; ' ORDER BY spellings)) END FROM clashes;
DELETE FROM acl."meta" WHERE "key" = 'min_reader_version';
INSERT INTO acl."meta" VALUES ('min_reader_version', '20');
UPDATE acl."meta" SET "value" = '20' WHERE "key" = 'schema_version';
