#!/usr/bin/env python3
"""Render schema/policy_schema.sql into what else needs it (spec 034).

The .sql file is the source of truth. This writes:

  src/include/acl_schema_sql.hpp   every statement the extension runs, placeholders intact
  schema/acl_schema.sql            the schema as it stands, names resolved - apply this to a fresh
                                   database and the extension will use what it finds
There are no migrations yet (no release): schema/migrations/README.md holds the contract the first
one will follow.

Both come from one file, so a hand-applied schema and the extension's own cannot drift apart.

Only the duckdb dialect is rendered. Translating to another one is left to whoever applies it, or
to a later step through a real translator (sqlglot and friends) - the schema is plain SQL, and a
hand-rolled per-dialect renderer is a second thing to keep correct for no gain. Where a target
genuinely differs the source file says so: `ACL_KEY_TEXT` marks the columns that carry an index,
which SQL Server needs bounded (spec 033).

Run `make schema` after editing the source; `make schema-check` fails when the outputs are stale.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "schema", "policy_schema.sql")
HEADER = os.path.join(ROOT, "src", "include", "acl_schema_sql.hpp")
APPLIABLE = os.path.join(ROOT, "schema", "acl_schema.sql")


def read_statements(path):
    """The source file as (section, comments, sql) triples, in order.

    A `;` at end of line ends a statement; `-- @section <name>` starts a section. `schema` is the
    tables as they are now, `migrations` only what an older catalog is missing - which is why a
    hand-applied schema needs the first section and none of the second.
    """
    statements = []
    comments = []
    buffer = ""
    section = "schema"
    seen_sql = False
    for line in open(path):
        stripped = line.strip()
        if not stripped:
            # a blank line ends the file's own header block; comments before the first statement
            # describe the file, not the statement that happens to follow
            if not seen_sql:
                comments = []
            continue
        if stripped.startswith("-- @section "):
            section = stripped[len("-- @section ") :].strip()
            comments = []
            continue
        if stripped.startswith("--"):
            if not buffer:
                comments.append(stripped[2:].strip())
            continue
        seen_sql = True
        buffer += (" " if buffer else "") + stripped
        if buffer.endswith(";"):
            statements.append((section, comments, buffer[:-1]))
            comments = []
            buffer = ""
    if buffer:
        raise SystemExit("gen_schema: unterminated statement: " + buffer[:60])
    return statements


def schema_version(statements):
    """The version the schema stamps into `meta` - the one statement that says what this shape is."""
    for _, _, sql in statements:
        found = re.search(r"'schema_version', '(\d+)'", sql)
        if found:
            return int(found.group(1))
    raise SystemExit("gen_schema: the schema does not stamp a schema_version")


def cpp_literal(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_header(statements):
    out = [
        "// Generated by scripts/gen_schema.py from schema/policy_schema.sql - do not edit.",
        "// Edit the .sql file and run `make schema` (spec 034).",
        "",
        "#pragma once",
        "",
        "namespace duckdb {",
        "namespace acl {",
        "",
        "//! The managed schema, in the order it must be applied. `<schema>` and `<table>` are",
        "//! substituted with the qualified names of the catalog being initialised, and ACL_KEY_TEXT",
        "//! with the key-column type that catalog's kind needs (spec 033).",
        "static const char *const ACL_SCHEMA_SQL[] = {",
    ]
    for _, _, sql in statements:
        out.append("    " + cpp_literal(sql) + ",")
    version = schema_version(statements)
    out += [
        "};",
        "",
        "//! The version this schema is. A catalog carries its own in `meta`, and a build refuses one",
        "//! that does not match: the migration contract rests on the two being comparable (spec 034).",
        "static constexpr int ACL_SCHEMA_VERSION = %d;" % version,]
    out += [
        "",
        "} // namespace acl",
        "} // namespace duckdb",
        "",
    ]
    open(HEADER, "w").write("\n".join(out))


def resolve_names(sql):
    """`<schema>` and `<table>` as a hand-applied file spells them: the schema `acl` of whatever
    database the file is run against."""
    return re.sub(r"<([a-z_]+)>", lambda m: "acl" if m.group(1) == "schema" else 'acl."%s"' % m.group(1), sql)


def write_appliable(statements):
    lines = [
        "-- duckdb-acl policy schema (spec 006), generated from schema/policy_schema.sql.",
        "-- Do not edit: run `make schema` after changing the source (spec 034).",
        "--",
        "-- duckdb dialect, ready to run as it stands: it creates the schema `acl` in the database you",
        "-- run it against, which is what `acl_use_db('<db>', 'acl', true)` would have created. Pass the",
        "-- same schema name to acl_use_db afterwards, with init disabled, and the extension will use it.",
        "--",
        "-- It is the schema as it stands - the migrations the extension also carries are for catalogs",
        "-- an older version created, and a schema applied from here needs none of them.",
        "--",
        "-- For another engine, translate it - the SQL is plain, and a translator (sqlglot and friends)",
        "-- handles it. Two things a target may need changing:",
        "--   * a key column (VARCHAR below, ACL_KEY_TEXT in the source) is indexed, so SQL Server needs",
        "--     it bounded - NVARCHAR(255) rather than NVARCHAR(MAX), which cannot carry an index;",
        "--   * `IF NOT EXISTS` on CREATE TABLE / ADD COLUMN is not universal - T-SQL guards instead.",
        "",
    ]
    for section, comments, sql in statements:
        for comment in comments:
            lines.append("-- " + comment)
        lines.append(resolve_names(sql).replace("ACL_KEY_TEXT", "VARCHAR") + ";")
        lines.append("")
    open(APPLIABLE, "w").write("\n".join(lines))


def main():
    statements = read_statements(SOURCE)
    write_header(statements)
    write_appliable(statements)
    print("gen_schema: %d statements -> acl_schema_sql.hpp + acl_schema.sql" % len(statements))


if __name__ == "__main__":
    sys.exit(main())
